site_name: trovu.net docs
site_description: your web search command line
site_url: https://trovu.net
repo_url: https://github.com/trovu/trovu
edit_uri: tree/master/docs/

docs_dir: docs
site_dir: dist/public/docs
theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.expand
    - navigation.footer
  font: false # Keep privacy and do not download external fonts.

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - minify:
      minify_html: true

# Navigation structure (if needed)
nav:
  - Home: index.md
  - privacy.md
  - User guide:
      - General: users/index.md
      - users/integration.md
      - users/advanced.md
      - users/troubleshooting.md
      - users/support.md
  - Shortcuts:
      - General: shortcuts/index.md
      - shortcuts/namespaces.md
      - shortcuts/url.md
      - shortcuts/include.md
      - shortcuts/deprecated.md
      - shortcuts/userscripts.md
      - shortcuts/tags.md
  - Editor guide:
      - General: editors/index.md
      - editors/policy.md
  - Developer guide:
      - developers/index.md
  - Legacy:
      - legacy/differences.md
      - legacy/migrate.md
      - presentations/index.md
  - alternatives.md
