name: Build and Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.6
      - uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: ${{ runner.os }}-pipenv-
      - run: pip install pipenv
      - run: pipenv install
      - run: pipenv run mkdocs build
      - uses: actions/setup-node@v4
        with:
          node-version: 21.3.0
      - run: npm clean-install
      - run: npm run build-jsdoc
      - run: npm run build-blog
      - run: npm run build
      - run: npm run lint-yaml
      - run: npm run validate-data
      - run: npm run compile-data
      - run: npm run test-unit
      - run: npm run test-calls
      - uses: actions/upload-artifact@v2
        with:
          name: public-directory
          path: dist/public/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.repository == 'trovu/trovu' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
        with:
          name: public-directory
          path: dist/public
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/public/
          repository-name: trovu/trovu-deploy
          branch: master
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          target-folder: ${{ (github.ref == 'refs/heads/master' && 'master') || 'dev' }}
          clean: true
